apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: InstagramScraper-deployment
spec:
  selector:
    matchLabels:
      app: InstagramScraper-project
  replicas: 2 # tells deployment to run 2 pods matching the template

  template:
    metadata:
      labels:
        app: InstagramScraper-project
    spec:
      containers:
      - name: InstagramScraper-project
        image: elin/InstagramScraper
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
